---
title: "AB323_bioptics"
output: html_document
date: "2026-04-29"
---

## load packages
```{r}
library(tidyverse)
library(readr)
library(readxl)
library(here)
```


## import data
```{r}
#setwd("C:/Users/Eva Samson/OneDrive - University of Bergen/Dokumenter/Bergen/AB-323/bioptics")

reflectance_raw <- read_xlsx("bioptics_reflectance_v2.xlsx", skip = 11) |> 
  select(!ID)

methanol_raw <- read_xlsx("bioptics_absorbance_v2.xlsx", skip = 11, sheet = "methanol extracts") |> 
  select(!ID)

water_raw <- read_xlsx("bioptics_absorbance_v2.xlsx", skip = 11, sheet = "water extracts") |> 
  select(!ID)

invivo_raw <- read_xlsx("bioptics_absorbance_v2.xlsx", skip = 11, sheet = "in vivo") |> 
  select(!ID)

filters_raw <- read_xlsx("bioptics_absorbance_v2.xlsx", skip = 11, sheet = "filters") |> 
  select(!ID)
```


## filters
```{r}
filters_PAR <- filters_raw |> 
  filter(400 <= wavelength, wavelength <= 700) |> 
  #select(!Astand_filter) |> 
  pivot_longer(cols = !wavelength, names_to = "sample", values_to = "value")
  # |> pivot_longer(cols = starts_with("A"), names_to = "sample", values_to = "value")


```


```{r}
filters_plot <- 
  ggplot(filters_PAR, 
         aes(x = wavelength, y= value, colour = sample)) +
  scale_color_viridis_d() +
  geom_line() +
  theme_minimal()

filters_plot

#ggsave(here("filters_plot.png"), plot = filters_plot, width = 120, height = 100, units = "mm", scale = 1.2)
```


## reflectance vs absorbance
```{r}
refl_brownalgae <- reflectance_raw |> 
  select(wavelength, contains("RB"))
abs_brownalgae <- invivo_raw |> 
  select(wavelength, contains("AB"))

refl_abs_brownalgae <- merge(refl_brownalgae, abs_brownalgae, by = "wavelength") |> 
  filter(400 <= wavelength, wavelength <= 700 ) |> 
  pivot_longer(cols = starts_with("RB") | starts_with("AB"), names_to = "sample", values_to = "value") |> 
  mutate(measurement = case_when(str_detect(sample, "R") ~ "reflectance", str_detect(sample, "A") ~ "absorbance"))


refl_abs_brownalgae_plot <- refl_abs_brownalgae |> 
  ggplot(aes(x = wavelength, y = value, color = sample)) + 
  geom_line() + 
  geom_line(data = subset(refl_abs_brownalgae, measurement == "absorbance"), aes(y = value*50)) +
  scale_color_viridis_d(option = "magma") +
  scale_y_continuous(sec.axis = sec_axis(~ . /50)) +
  theme_minimal()


refl_abs_brownalgae_plot

#ggsave(here("refl_abs_brownalgae_plot.png"), plot = refl_abs_brownalgae_plot, width = 120, height = 100, units = "mm", scale = 1.2)
```

## absorbance/reflectance
```{r}
abs_refl_ratio <- refl_abs_brownalgae |> 
  filter(sample == "RB1"| sample == "AB3") |> 
  pivot_wider(names_from = measurement, values_from = value) |> 
  #group_by(sample)
  mutate(ratio = )

```


for separating by class:
```{r}
mutate(class = case_when( str_detect(sample, "B") ~ "brown", str_detect(sample, "G") ~ "green", str_detect(sample, "AR|RR") ~ "red" )) 
```
sample modifications:
```{r}
#  filter(chl_a_ug_l_1 != "#VALUE!") |> 
#  filter(sampling_date == "24.04.2026") |> 
#  filter(filter == "GFF") |> 
#  filter(station == "Pier") |> 
#  mutate(chl_a_ug_l_1 = as.numeric(chl_a_ug_l_1)) |>
#  mutate(sample_depth_m = as.character(sample_depth_m)) |> 
#  group_by(sample_depth_m)
```

